config/routes.rb
Editor::Application.routes.draw do
  resources :elements

   root :to => "elements#index"

end

app/models/element.rb
class Element < ActiveRecord::Base
  attr_accessible :title, :name, :type_el

  validates :type_el,
      :presence => true,
      :format => {:with => /(radio|reset|text|checkbox)/}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController

  before_filter :load

  def load
    @elements = Element.all
    @element = Element.new
  end

  def index
  end

  def create
    @element = Element.new(params[:element])
    if @element.save
      flash[:notice] = "Successfully created element."
      @elements = Element.all
    end
  end

  def edit
    @element = Element.find(params[:id])
  end

  def update
    @element = Element.find(params[:id])
    if @element.update_attributes(params[:element])
      flash[:notice] = "Successfully updated element."
      index
      @elements = Element.all
    end
  end

  def destroy
    @element = Element.find(params[:id])
    @element.destroy
    flash[:notice] = "Successfully destroyed element."
    @elements = Element.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/elements/_elements.html.erb
  <% for element in @elements %>
      <%= link_to "Edit", edit_element_path(element), :remote => true %>    |
      <%= link_to "Destroy", element, :remote => true, :method => :delete %>  |
      <input name="<%= element.name %>" type="<%= element.type_el %>" value="<%= element.title %>">
    <br />
  <% end %>

app/views/elements/_form.html.erb
<%= form_for(@element, :remote => true) do |f| %>
  <div id= "element_errors" style="display:none"></div>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :type_el, "Input type (radio, reset, text, checkbox)" %><br />
    <%= f.text_field :type_el %>
  </p>
    <p><%= f.submit %></p>
<% end %>

app/views/elements/create.js.erb
<% if @element.errors.any? -%>
  /*Hide the flash notice div*/
  $("#flash_notice").hide(300);

  /*Update the html of the div post_errors with the new one*/
  $("#element_errors").html("<%= escape_javascript(error_messages_for(@element))%>");

  /*Show the div element_errors*/
  $("#element_errors").show(300);
<% else -%>
  /*Hide the div element_errors*/
  $("#element_errors").hide(300);

  /*Update the html of the div flash_notice with the new one*/
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");

  /*Show the flash_notice div*/
  $("#flash_notice").show(300);

  /*Clear the entire form*/
  $(":input:not(input[type=submit])").val("");

  /*Replace the html of the div element_lists with the updated new one*/
  $("#elements_list").html("<%= escape_javascript( render(:partial => "elements") ) %>");
<% end -%>

app/views/elements/destroy.js.erb
$("#element_errors").hide(300);
$("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");
$("#flash_notice").show(300);
$("#elements_list").html("<%= escape_javascript( render(:partial => "elements") ) %>");

app/views/elements/edit.js.erb
$("#element_form").html("<%= escape_javascript(render(:partial => "form"))%>");

app/views/elements/index.html.erb
<% title "Elements" %>

<div id="element_form"><%= render :partial => 'form' %></div>
<div id="elements_list"><%= render :partial => "elements" %></div>

app/views/elements/update.js.erb
<% if @element.errors.any? -%>
  $("#flash_notice").hide(300);
  $("#element_errors").html("<%= escape_javascript(error_messages_for(@element))%>");
  $("#element_errors").show(300);
<% else -%>
  $("#element_errors").hide(300);
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");
  $("#flash_notice").show(300);
  $(":input:not(input[type=submit])").val("");
  $("#element_form").html("<%= escape_javascript( render(:partial => "form") ) %>");
  $("#elements_list").html("<%= escape_javascript( render(:partial => "elements") ) %>");
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :all %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
   <body>
    <div id="container">
      <div id="flash_notice" style="display:none"></div>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>